spring:
  application:
    name: file-nest
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
security:
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods:
      GET,
      POST,
      OPTIONS
  permitted-urls:
    /api/auth/login,
    /api/auth/register,
    /v3/api-docs/**,
    /v3/api-docs.yaml,
    /swagger-ui/**,
    /swagger-ui.html
